language: node_js

dist: bionic

node_js:
  - 12.16.2

jobs:
  include:
    - name: "Jest + Enzyme Tests"
      script:
        - npm install
        - npm run test # -- --coverage --collectCoverageFrom='["src/Components/**/*.js", "!node_modules/**", "!src/__tests__/**"]' --watchAll
    - name: "Linter"
      script:
        - npm install
        - npm run eslint
